global:
  scrape_interval: 5s

remote_write:
  - url: "https://prometheus-prod-XX.grafana.net/api/prom"
    basic_auth:
      username: "admin"
      password: "admin"

scrape_configs:
  - job_name: 'notes-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']